name: experimento-ci-cd

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências do backend
        working-directory: ./backend
        run: npm ci

      - name: Executar testes unitários com Jest
        working-directory: ./backend
        run: npm test -- --coverage

  # Unificado: O build e o up precisam acontecer na mesma máquina (runner)
  build-and-integration:
    needs: unit-test
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: adote_facil
      POSTGRES_HOST: adote-facil-postgres
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_PORT: 5432
      POSTGRES_CONTAINER_PORT: 6500
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar arquivo .env
        run: |
          # Garante que a pasta existe e cria o arquivo com aspas para proteger as senhas
          mkdir -p backend
          echo "POSTGRES_DB='${{ env.POSTGRES_DB }}'" > ./backend/.env
          echo "POSTGRES_HOST='${{ env.POSTGRES_HOST }}'" >> ./backend/.env
          echo "POSTGRES_USER='${{ env.POSTGRES_USER }}'" >> ./backend/.env
          echo "POSTGRES_PASSWORD='${{ env.POSTGRES_PASSWORD }}'" >> ./backend/.env
          echo "POSTGRES_PORT='${{ env.POSTGRES_PORT }}'" >> ./backend/.env
          echo "POSTGRES_CONTAINER_PORT='${{ env.POSTGRES_CONTAINER_PORT }}'" >> ./backend/.env

      - name: Build e Up dos Containers
        run: |
          docker compose build
          docker compose up -d
          # Espera ativa (futuramente podemos trocar por um curl verificando a saúde real da API)
          sleep 15
          docker compose down

  delivery:
    needs: build-and-integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar arquivo ZIP do projeto completo
        run: zip -r adote-facil-projeto.zip . -x '*.git*' '*.github*' 'node_modules/*'

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: adote-facil-projeto
          path: adote-facil-projeto.zip